### ISSUE TITLE
Visualization of the scalar- or vector features

### ISSUE THREAD

**Issue by MingyuLiu1** [rubenwiersma/deltaconv#5]
Hi, first of all thanks for sharing the great work! 
I am quite interested in the visualization of the single scalar- or vector feature of each layer (figure 5 in the paper). Can you please also release the codes for the visualization? Thanks a lot!

**Comment by rubenwiersma** [comment]
Hi MingyuLiu1,

Thanks for the kind comments! I've added the folder [visualization](https://github.com/rubenwiersma/deltaconv/tree/master/visualization) that explains the process to render figure 5 and includes links to the Blender files used to render figure 5 and some scripts to export features in the network to a .ply file. I would advise using [Blender Toolbox](https://github.com/HTDerekLiu/BlenderToolbox) if I were to render the figures now. There are also links to relevant demos and other alternatives in the README.md in the [visualization folder](https://github.com/rubenwiersma/deltaconv/tree/master/visualization).

Hope this helps!

Best,

Ruben

**Comment by MingyuLiu1** [comment]
Hi Ruben,

Thanks for your quick reply :D. It is appreciated! I will follow your suggestion to do the visualization. 

Best,
Mingyu
